[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 5

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#b48cff"
backgroundColor = "#0b0716"
secondaryBackgroundColor = "#17102b"
textColor = "#ece4ff"
font = "sans serif"
