[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 5

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#d97757"
backgroundColor = "#131314"
secondaryBackgroundColor = "#1e1f20"
textColor = "#e3e3e3"
borderColor = "#2e2f31"
dataframeBorderColor = "#2e2f31"
baseRadius = "0.75rem"
showWidgetBorder = true
font = "sans serif"
